### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by hemanth** [fp-js/meta#2]
Modules in here starts with `fp-` and those in Dom with `fd-` makes sense ?

**Comment by stoeffel** [comment]
or in **_f**_p-**_j**_s `fj`
and in **_f**_p-**_d**_om `fd`

**Comment by hemanth** [comment]
`fj`, `fd` yup. :+1:

**Comment by stoeffel** [comment]
I will rename...

**Comment by hemanth** [comment]
Awesome! Sorry about the confusion :(

**Comment by stoeffel** [comment]
done

**Comment by hemanth** [comment]
:+1:
