### ISSUE TITLE
indexed vs non-indexed iterations.

### ISSUE THREAD

**Issue by hemanth** [fp-js/meta#3]
Would it makes sense to have seprate functions for indexed based iteration and non-indexed based.

What would you vote for and why?

//cc @stoeffel

**Comment by stoeffel** [comment]
I'm pro non-indexed.
Because, without the index you can do:

``` js
map(parseInt, arr);
```

And we could create a function `indexify`.
Indexify would work like this:

``` js
const a = ["foo", "bar", "moo"];
const aIdxd = indexify(a);
console.log(aIdxd); // => [[0, "foo"], [1, "bar"], [2, "moo"]]

map((i) => i[0] + i[1], aIdxd); // => ["0foo", "1bar", "2moo"]
```

**Comment by stoeffel** [comment]
@hemanth I will create `indexify` if you agree to ^.

**Comment by hemanth** [comment]
SGTM :+1:
